name: CI

on:
  push:

jobs:
  test:
    runs-on: codebuild-ubuntu-small-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - run: echo "hello from code build"
        shell: bash
      - run: echo "$(docker version)"
        shell: bash
      - run: echo "$(id -u)"
        shell: bash
      - run: echo "$(whoami)"
        shell: bash
      - run: |
          echo "daemon.json:"
          cat /etc/docker/daemon.json
          echo "network ls:"
          docker network ls
          echo "network inspect bridge:"
          docker network inspect bridge

  test2:
    runs-on: ubuntu-22.04
    steps:
      - run: echo "hello from github actions"
        shell: bash
      - run: echo "$(docker version)"
        shell: bash
      - run: echo "$(id -u)"
        shell: bash
      - run: echo "$(whoami)"
        shell: bash
      - run: |
          echo "daemon.json:"
          cat /etc/docker/daemon.json
          echo "network ls:"
          docker network ls
          echo "network inspect bridge:"
          docker network inspect bridge
