name: CI

on:
  push:

jobs:
  test:
    runs-on: codebuild-ubuntu-small-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - run: echo "hello from code build"
        shell: bash
      - run: echo "$(docker version)"
        shell: bash
      - run: echo "$(id -u)"
        shell: bash
      - run: echo "$(whoami)"
        shell: bash
      - run: |
          echo "network ls:"
          docker network ls
          echo "network inspect bridge:"
          docker network inspect bridge
          echo "ipv6 pin:"
          docker run --rm busybox ping6 -c 4 ipv6.google.com

  test2:
    runs-on: ubuntu-22.04
    steps:
      - run: echo "hello from github actions"
        shell: bash
      - run: echo "$(docker version)"
        shell: bash
      - run: echo "$(id -u)"
        shell: bash
      - run: echo "$(whoami)"
        shell: bash
      - run: |
          echo "network ls:"
          docker network ls
          echo "network inspect bridge:"
          docker network inspect bridge
          echo "ipv6 pin:"
          docker run --rm busybox ping6 -c 4 ipv6.google.com
          sudo mkdir -p /etc/docker
          echo '{"ipv6":true,"fixed-cidr-v6":"fd9a:8454:6789:13f7::/64"}' \
              | sudo tee /etc/docker/daemon.json
          sudo service docker restart
